//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VscApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverInfo
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerID { get; set; }
        public string RouteID { get; set; }
        public string RouteName { get; set; }
        public string PlannedStartDate { get; set; }
        public string PlannedEndDate { get; set; }
        public string DepotID { get; set; }
        public string DepotName { get; set; }
        public string DriverID { get; set; }
        public string DriverName { get; set; }
        public string DriverReference { get; set; }
        public string DriverTag { get; set; }
        public string StopElementID { get; set; }
        public string SequenceNo { get; set; }
        public string PlannedArrivalTime { get; set; }
        public string PlannedDepartureTime { get; set; }
        public string LocationName { get; set; }
        public string HasArrived { get; set; }
        public string HasDeparted { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    }
}
